[package]
name = "ci"
version = "0.1.0"
authors = ["Martin Krošlák <kroslakma@gmail.com>"]

[dependencies]

[dev-dependencies]
minreq = { version = "^1.1.0", features = ["https"] }
ron = "^0.4"
serde = "^1.0.75"
serde_derive = "^1.0.75"
vk-parse = { path = "../vk-parse" }
vkxml = "^0.3"
xml-rs = "^0.8"
# cargo +nightly update -Z minimal-versions && cargo update --package log --precise 0.4.4
